### ISSUE TITLE
Socket error on Azure app service

### ISSUE THREAD

**Issue by theguy69** [robertvazan/guerrillantp-cli#1]
I'm getting this error:

Error: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10014): The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:194.117.47.42]:123
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at GuerrillaNtp.NtpClient.Connect()
   at GuerrillaNtp.NtpClient.Query()

When using in a Azure App, running local don't throw error.

Code used

//NtpClient client = new NtpClient("ntp02.oal.ul.pt");
NtpClient client = new NtpClient(IPAddress.Parse("194.117.47.42"));
NtpClock clock = client.Query();

Any idea how to solve this?

Cheers

Jorge

**Comment by theguy69** [comment]
By mistake this issue was opended in -cli and not on the .net component, adding the issue to the correct repo
